import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  await prisma.user.createMany({
    data: [
     {
      nik: "3174011908160007",
      name: "Davian arman p",
      gender: "Laki - Laki",
      birthDate: new Date("2016-08-19"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174014705160003",
      name: "Aninditha Revalina",
      gender: "Perempuan",
      birthDate: new Date("2016-05-07"),
      school: "SDN 01",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "317401051170004",
      name: "Abdul Hakim",
      gender: "Laki - Laki",
      birthDate: new Date("2017-11-05"),
      school: "SDN 01",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012203160005",
      name: "M fadel riyansyah",
      gender: "Laki - Laki",
      birthDate: new Date("2016-03-22"),
      school: "SDN 01",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174011907141005",
      name: "Bobby janitra ramadhan",
      gender: "Laki - Laki",
      birthDate: new Date("2014-07-19"),
      school: "SDN 03",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174025011150004",
      name: "Kayla Humaira Idris",
      gender: "Laki - Laki",
      birthDate: new Date("2015-11-10"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3527012505130002",
      name: "Moh Zidan Latif",
      gender: "Laki - Laki",
      birthDate: new Date("2013-05-25"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010810180012",
      name: "Beryl Shaquille rabbani",
      gender: "Laki - Laki",
      birthDate: new Date("2018-10-08"),
      school: "SDN 03",
      class: "1",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3527011001170001",
      name: "Faizul Anwar",
      gender: "Laki - Laki",
      birthDate: new Date("2017-01-10"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012903151003",
      name: "Nata pradata bill ardis",
      gender: "Laki - Laki",
      birthDate: new Date("2015-03-29"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3201161405150005",
      name: "Fabian gibran azzura",
      gender: "Laki - Laki",
      birthDate: new Date("2015-05-14"),
      school: "SDN 03",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174025006151003",
      name: "Anindya faradiba azzahra",
      gender: "Perempuan",
      birthDate: new Date("2015-06-10"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014712141003",
      name: "Desvia ayunindya zaida",
      gender: "Perempuan",
      birthDate: new Date("2014-12-07"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010808141003",
      name: "Fathir Al baddin purnoyudho",
      gender: "Laki - Laki",
      birthDate: new Date("2014-08-08"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011205170007",
      name: "Fathar ghaneem purnoyudho",
      gender: "Laki - Laki",
      birthDate: new Date("2017-05-12"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010201160005",
      name: "AGAM ADITYA WAHYUDI",
      gender: "Laki - Laki",
      birthDate: new Date("2016-01-02"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010403141003",
      name: "AHMAD GHAFFAR ALI",
      gender: "Laki - Laki",
      birthDate: new Date("2014-03-04"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3171070910141001",
      name: "MUHAMMAD RIZKY FACHLAN",
      gender: "Laki - Laki",
      birthDate: new Date("2014-10-09"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015510141002",
      name: "REVA ERLIANTI PUTRI",
      gender: "Perempuan",
      birthDate: new Date("2014-10-15"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174017108160004",
      name: "RAISYA PUTRI FACHLAN",
      gender: "Perempuan",
      birthDate: new Date("2016-08-31"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011505170001",
      name: "Muhammad Haikal Faraja",
      gender: "Laki - Laki",
      birthDate: new Date("2017-05-15"),
      school: "Lainya",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016708151001",
      name: "CAHAYA KAMILA PUTRI",
      gender: "Perempuan",
      birthDate: new Date("2015-08-27"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3171065801141001",
      name: "KINTANIA JELITA AZAHRA",
      gender: "Perempuan",
      birthDate: new Date("2014-01-18"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174026112150002",
      name: "Anindita Keysha Zahra",
      gender: "Perempuan",
      birthDate: new Date("2015-12-21"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014407141003",
      name: "NAYLA PUTRI KHUMAIRAH",
      gender: "Perempuan",
      birthDate: new Date("2014-07-04"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016011150001",
      name: "VIXIE ORLYN",
      gender: "Perempuan",
      birthDate: new Date("2015-11-20"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174017010141004",
      name: "Syanala Kania Salsabila",
      gender: "Perempuan",
      birthDate: new Date("2014-10-30"),
      school: "SDN 03",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012703131001",
      name: "AFGHAN DWIPUTRA",
      gender: "Laki - Laki",
      birthDate: new Date("2013-03-27"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014906160002",
      name: "MUFRIDA RAMADHANIA PUTRI",
      gender: "Perempuan",
      birthDate: new Date("2016-06-09"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015105131001",
      name: "Rima Mei Dina",
      gender: "Perempuan",
      birthDate: new Date("2013-05-11"),
      school: "SDN 03",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Belum",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174015002170009",
      name: "Anindira Riani",
      gender: "Perempuan",
      birthDate: new Date("2017-02-10"),
      school: "SDN 03",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "317405305180002",
      name: "AKIFAH SHALiHA KHASIEB",
      gender: "Perempuan",
      birthDate: new Date("2018-05-13"),
      school: "Lainya",
      class: "1",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012009121002",
      name: "Aditya Bayu Septian",
      gender: "Laki - Laki",
      birthDate: new Date("2012-09-20"),
      school: "SDN 03",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174011307151002",
      name: "Ando Ramadhan",
      gender: "Laki - Laki",
      birthDate: new Date("2015-07-13"),
      school: "SDN 03",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012107141002",
      name: "Davfa Frandana",
      gender: "Laki - Laki",
      birthDate: new Date("2014-07-21"),
      school: "SDN 03",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012505151002",
      name: "Aldro Mandala Samosir",
      gender: "Laki - Laki",
      birthDate: new Date("2015-05-25"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016702141001",
      name: "Asyla Febriana Samosir",
      gender: "Perempuan",
      birthDate: new Date("2014-02-27"),
      school: "SDN 03",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Belum",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174010410141006",
      name: "Khalifah Derren Tandere",
      gender: "Laki - Laki",
      birthDate: new Date("2014-10-04"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015102180005",
      name: "Sheren Fazia Halinka",
      gender: "Perempuan",
      birthDate: new Date("2018-02-11"),
      school: "Lainya",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015304160001",
      name: "Aurelia Anindya suseno",
      gender: "Perempuan",
      birthDate: new Date("2016-04-13"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010307151003",
      name: "IBRAHIM ALEXI PRATAMA",
      gender: "Laki - Laki",
      birthDate: new Date("2015-07-03"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014309160001",
      name: "KANAYA SALSA BILA AYU PUTRI",
      gender: "Perempuan",
      birthDate: new Date("2016-09-03"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015807111009",
      name: "Fajriah Nurhayatj",
      gender: "Perempuan",
      birthDate: new Date("2011-07-18"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015611121008",
      name: "Wasilah Dwi Wahyuni",
      gender: "Perempuan",
      birthDate: new Date("2012-11-16"),
      school: "SDN 03",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012505160003",
      name: "MUHAMMAD AZKA ZAIDAN",
      gender: "Laki - Laki",
      birthDate: new Date("2016-05-25"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014207151002",
      name: "Khaynada Inara Felisha Prasetyo",
      gender: "Perempuan",
      birthDate: new Date("2015-07-02"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012506170001",
      name: "GALU TRI SAPUTRA",
      gender: "Laki - Laki",
      birthDate: new Date("2017-06-25"),
      school: "Lainya",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014611141006",
      name: "Nazwa fussilat hanifa",
      gender: "Perempuan",
      birthDate: new Date("2014-11-06"),
      school: "SDIT Assyafi'iyah",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011203170003",
      name: "MUHAMMAD ZIDANE ZIDAN",
      gender: "Laki - Laki",
      birthDate: new Date("2017-07-12"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016007170003",
      name: "Nadeera falisha Zahra",
      gender: "Perempuan",
      birthDate: new Date("2017-07-20"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "317401070616002",
      name: "Mora anindito",
      gender: "Laki - Laki",
      birthDate: new Date("2016-06-07"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011004131002",
      name: "RIZKAL MAHESA PUTRA",
      gender: "Laki - Laki",
      birthDate: new Date("2013-04-10"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174015011160006",
      name: "Kirana Putri Erhansyah",
      gender: "Perempuan",
      birthDate: new Date("2016-11-10"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3326095811170003",
      name: "NOVIA MAULIDA",
      gender: "Perempuan",
      birthDate: new Date("2017-11-18"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016709170002",
      name: "AURA BUNGA AUDI",
      gender: "Perempuan",
      birthDate: new Date("2017-09-27"),
      school: "SDN 01",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Sudah",
      imunHPV6: "Sudah",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010907170001",
      name: "Muhammad al fathan",
      gender: "Laki - Laki",
      birthDate: new Date("2017-07-09"),
      school: "Lainya",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010109131004",
      name: "MUHAMAD ADI RAMDANI",
      gender: "Laki - Laki",
      birthDate: new Date("2013-09-01"),
      school: "Lainya",
      class: "6",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3173076609160003",
      name: "SYAFIRA ADININGTYAS",
      gender: "Perempuan",
      birthDate: new Date("2016-09-26"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010703131003",
      name: "Yohanes abraham eko siwa",
      gender: "Laki - Laki",
      birthDate: new Date("2013-03-07"),
      school: "SDN 01",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174011802151003",
      name: "ADNAN MIRZA UKAIL",
      gender: "Laki - Laki",
      birthDate: new Date("2015-02-18"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3276071612120003",
      name: "RIO RACHMADI",
      gender: "Laki - Laki",
      birthDate: new Date("2016-12-16"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Sudah",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174026403160001",
      name: "Miranda Ester Sitinjak",
      gender: "Perempuan",
      birthDate: new Date("2025-07-03"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Belum",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174014203141002",
      name: "Melody Puspa Aqueena",
      gender: "Perempuan",
      birthDate: new Date("2014-03-02"),
      school: "Lainya",
      class: "6",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015507141001",
      name: "RESISTA OLIVIA",
      gender: "Perempuan",
      birthDate: new Date("2014-07-15"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174022807160003",
      name: "Julio Haris",
      gender: "Laki - Laki",
      birthDate: new Date("2016-07-28"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3175011311151002",
      name: "WAHYU SHUBUH HIDAYAT",
      gender: "Laki - Laki",
      birthDate: new Date("2015-11-13"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010310160003",
      name: "Rafardhan Bagja Alfatih",
      gender: "Laki - Laki",
      birthDate: new Date("2016-10-03"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174025202141004",
      name: "Melinda Danesh Sitinjak",
      gender: "Perempuan",
      birthDate: new Date("2014-02-12"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Sudah",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174010301151003",
      name: "Muhamad Rojak fuad",
      gender: "Laki - Laki",
      birthDate: new Date("2015-01-03"),
      school: "SDIT Assyafi'iyah",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014906180007",
      name: "Razita Hegar Salsabila",
      gender: "Perempuan",
      birthDate: new Date("2018-06-09"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010702141007",
      name: "REVAN ALFATHIR LUFIAN",
      gender: "Laki - Laki",
      birthDate: new Date("2014-02-07"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174016303180003",
      name: "Anindita Keisha Zahra",
      gender: "Perempuan",
      birthDate: new Date("2018-03-23"),
      school: "Lainya",
      class: "1",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174026403160001",
      name: "Miranda Ester Sitinjak",
      gender: "Perempuan",
      birthDate: new Date("2016-03-24"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010111160001",
      name: "Hafizh Prataya",
      gender: "Laki - Laki",
      birthDate: new Date("2016-11-01"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011704111005",
      name: "fADIL AhwAL ShAHID",
      gender: "Laki - Laki",
      birthDate: new Date("2017-03-08"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011601170005",
      name: "FAHREZA SHABIR ALHAKIM",
      gender: "Laki - Laki",
      birthDate: new Date("2017-01-16"),
      school: "Lainya",
      class: "3",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3164015509180006",
      name: "Gikaela Allyssa",
      gender: "Perempuan",
      birthDate: new Date("2018-09-15"),
      school: "Lainya",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174084211151002",
      name: "Samantha Pius Budihartono",
      gender: "Perempuan",
      birthDate: new Date("2015-11-02"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014206241004",
      name: "NADIRATHAFANA KHARISMAWATI",
      gender: "Perempuan",
      birthDate: new Date("2014-06-02"),
      school: "SDN 01",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012307160004",
      name: "AHMAD FAJRI",
      gender: "Laki - Laki",
      birthDate: new Date("2016-07-23"),
      school: "SDN 03",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011704111005",
      name: "SYARIF AFRIANSYSH",
      gender: "Laki - Laki",
      birthDate: new Date("2011-04-17"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174105508131003",
      name: "Naura aila nahda",
      gender: "Perempuan",
      birthDate: new Date("2013-08-15"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Belum",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3306090908170002",
      name: "Muhammad Zaki Aiman",
      gender: "Laki - Laki",
      birthDate: new Date("2017-08-09"),
      school: "SDN 01",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015504141001",
      name: "Auzillia Bilqis Cahaya Fajar .M.",
      gender: "Perempuan",
      birthDate: new Date("2014-04-15"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010705151001",
      name: "Muhammad Akbar",
      gender: "Laki - Laki",
      birthDate: new Date("2015-05-07"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3171036309170003",
      name: "Kanaya nadwa albar",
      gender: "Perempuan",
      birthDate: new Date("2017-09-23"),
      school: "Lainya",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016305180007",
      name: "Faihalwa Qiura azarein",
      gender: "Perempuan",
      birthDate: new Date("2018-05-23"),
      school: "Lainya",
      class: "1",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011312121010",
      name: "Muhammad Rizky Pratama",
      gender: "Laki - Laki",
      birthDate: new Date("2012-12-13"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Sudah",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174045807170003",
      name: "Kanzia Azzahra",
      gender: "Perempuan",
      birthDate: new Date("2017-07-18"),
      school: "Lainya",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174081306151004",
      name: "Muhammad Nazril",
      gender: "Laki - Laki",
      birthDate: new Date("2015-08-13"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014707141002",
      name: "Kinara Adzra Ramadhani",
      gender: "Perempuan",
      birthDate: new Date("2014-07-07"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010305170003",
      name: "Muhammad Gathan Al Farizi",
      gender: "Laki - Laki",
      birthDate: new Date("2017-05-03"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012311180001",
      name: "Hafiz Fahreza",
      gender: "Laki - Laki",
      birthDate: new Date("2018-06-23"),
      school: "Lainya",
      class: "1",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016903131006",
      name: "Farah luthfiyah",
      gender: "Perempuan",
      birthDate: new Date("2013-03-29"),
      school: "SDN 01",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Belum",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174014203141007",
      name: "Haura Fayhaza Hannani",
      gender: "Perempuan",
      birthDate: new Date("2014-03-02"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016401160003",
      name: "Hasnah khayyirah shatiyyah",
      gender: "Perempuan",
      birthDate: new Date("2016-01-24"),
      school: "SDN 01",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012307141006",
      name: "Mirza rabbani ramadhan",
      gender: "Laki - Laki",
      birthDate: new Date("2014-07-23"),
      school: "SDN 01",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3175022012131004",
      name: "Mohammad Ghaly Ahsan",
      gender: "Laki - Laki",
      birthDate: new Date("2013-12-20"),
      school: "SDN 01",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174012807170002",
      name: "MUHAMAD NIZAM SAPUTRA",
      gender: "Laki - Laki",
      birthDate: new Date("2017-07-28"),
      school: "SDN 03",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014203141007",
      name: "Haura Fayhaza Hannani",
      gender: "Perempuan",
      birthDate: new Date("2014-03-02"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
],
    skipDuplicates: true,
  });
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
