import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  await prisma.user.createMany({
    data: [
     {
      nik: "3174010511170004",
      name: "ABDUL HAKIM",
      gender: "Laki - Laki",
      birthDate: new Date("2017-05-11"),
      school: "SDN 01",
      class: "1",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174020404170001",
      name: "ACHMAD AZZAM FATURAHMAN",
      gender: "Laki - Laki",
      birthDate: new Date("2017-04-04"),
      school: "SDN 01",
      class: "1",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012208170006",
      name: "ADRIAN PRADIPTA AMZARIL",
      gender: "Laki - Laki",
      birthDate: new Date("2017-08-22"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011606160001",
      name: "ALDI SYAHRI RAMADHAN",
      gender: "Laki - Laki",
      birthDate: new Date("2016-06-16"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3216062508170004",
      name: "Althaf Dhafin Assidik",
      gender: "Laki - Laki",
      birthDate: new Date("2017-08-25"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014510170009",
      name: "Annasya Adreena Saila",
      gender: "Perempuan",
      birthDate: new Date("2017-10-05"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015208170003",
      name: "Arsyila Romeesa Farzana",
      gender: "Perempuan",
      birthDate: new Date("2017-08-12"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014610170002",
      name: "ASHILA HAURA AZIZAH",
      gender: "Perempuan",
      birthDate: new Date("2017-10-06"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011711170005",
      name: "Azka Alkhair",
      gender: "Laki - Laki",
      birthDate: new Date("2017-11-17"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015506170005",
      name: "Dervila Labibah",
      gender: "Perempuan",
      birthDate: new Date("2017-06-15"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011402180001",
      name: "Faiz Haidar Adinata",
      gender: "Laki - Laki",
      birthDate: new Date("2018-02-14"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014809170004",
      name: "Fateen Almeera Amin",
      gender: "Perempuan",
      birthDate: new Date("2017-09-08"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3275046305170006",
      name: "Jessy Alberga Kamalsah",
      gender: "Perempuan",
      birthDate: new Date("2017-05-23"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014907170005",
      name: "KHANSA CAMELIA",
      gender: "Perempuan",
      birthDate: new Date("2017-07-09"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016504170002",
      name: "Mauliya Aprila Dewi",
      gender: "Perempuan",
      birthDate: new Date("2017-04-25"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012411170002",
      name: "Muhammad Abidzar Aqil Abziansyah",
      gender: "Laki - Laki",
      birthDate: new Date("2017-11-24"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012302170002",
      name: "Muhammad Arham Fadilah",
      gender: "Laki - Laki",
      birthDate: new Date("2017-02-23"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "1213010908170001",
      name: "MUHAMMAD SHAMEER NASRY",
      gender: "Laki - Laki",
      birthDate: new Date("2017-08-09"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3306090908170002",
      name: "MUHAMMAD ZAKI AIMAN",
      gender: "Laki - Laki",
      birthDate: new Date("2017-08-09"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015407170003",
      name: "NADITA WULANDARI AYU KENCANA",
      gender: "Perempuan",
      birthDate: new Date("2017-07-14"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016409170003",
      name: "NASYITA SHAFWATUNNISA",
      gender: "Perempuan",
      birthDate: new Date("2017-09-24"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010306170001",
      name: "RAFFASYA RAZKA RAMAZAN",
      gender: "Laki - Laki",
      birthDate: new Date("2017-06-03"),
      school: "SDN 01",
      class: "1",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "7304071207170002",
      name: "Rajendra Arthur Rakabumi",
      gender: "Laki - Laki",
      birthDate: new Date("2017-07-12"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011911170003",
      name: "RASYID GHIFARI RAFFASYA",
      gender: "Laki - Laki",
      birthDate: new Date("2017-11-19"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014301180002",
      name: "REVINA ANGGRAINI",
      gender: "Perempuan",
      birthDate: new Date("2018-01-03"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015207170001",
      name: "SHAFANA ZAHRATUL JANNAH",
      gender: "Perempuan",
      birthDate: new Date("2017-07-12"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174017103170007",
      name: "SITI ADINDA ANNUR",
      gender: "Perempuan",
      birthDate: new Date("2017-03-31"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016712160001",
      name: "VANIYA AYUDIA AQILA",
      gender: "Perempuan",
      birthDate: new Date("2016-12-27"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012407170005",
      name: "ABDULLAH MUHAMMAD GHAZALI",
      gender: "Laki - Laki",
      birthDate: new Date("2017-07-24"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010601170002",
      name: "Achmad Rafli Syah",
      gender: "Laki - Laki",
      birthDate: new Date("2017-01-06"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011706170004",
      name: "AHMAD ALIF FAUZI",
      gender: "Laki - Laki",
      birthDate: new Date("2017-06-17"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016212160002",
      name: "ANINDITA ZAHRA",
      gender: "Perempuan",
      birthDate: new Date("2016-12-22"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014611170007",
      name: "Aqilla Az Zahra",
      gender: "Perempuan",
      birthDate: new Date("2017-11-06"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014908170001",
      name: "ARUNA SACHI KAYANA",
      gender: "Perempuan",
      birthDate: new Date("2017-08-09"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016709170002",
      name: "AURA BUNGA AUDI",
      gender: "Perempuan",
      birthDate: new Date("2017-09-27"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012607160003",
      name: "AZKA RAFFASYA",
      gender: "Laki - Laki",
      birthDate: new Date("2016-07-26"),
      school: "SDN 01",
      class: "1",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016808170004",
      name: "Azkhaira Yasna Malaika",
      gender: "Perempuan",
      birthDate: new Date("2017-08-28"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012303180002",
      name: "El Sayyidina Robani",
      gender: "Laki - Laki",
      birthDate: new Date("2018-03-23"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016102170004",
      name: "FARADILLAH INDIRA",
      gender: "Perempuan",
      birthDate: new Date("2017-02-21"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012203170001",
      name: "HABIBIE SATRIO",
      gender: "Laki - Laki",
      birthDate: new Date("2017-03-22"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174045807170003",
      name: "KANZIA AZZAHRA MAULANA",
      gender: "Perempuan",
      birthDate: new Date("2017-07-18"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016010160005",
      name: "LIVIA JESLLYN",
      gender: "Perempuan",
      birthDate: new Date("2016-10-20"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010902180008",
      name: "Muhamad Fathan Fahreza",
      gender: "Laki - Laki",
      birthDate: new Date("2018-02-09"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011303170004",
      name: "Muhammad Abyan Nandana",
      gender: "Laki - Laki",
      birthDate: new Date("2017-03-13"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010506170006",
      name: "MUHAMMAD RAJA RAMADHAN",
      gender: "Laki - Laki",
      birthDate: new Date("2017-06-05"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011907170003",
      name: "MUHAMMAD SYAFIQ AL AYYASI",
      gender: "Laki - Laki",
      birthDate: new Date("2017-07-19"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016604170006",
      name: "MUTIA NUR KAYSHA",
      gender: "Perempuan",
      birthDate: new Date("2017-04-26"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015101180001",
      name: "Nanda Salsabila",
      gender: "Perempuan",
      birthDate: new Date("2018-01-11"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010410170001",
      name: "NATTA BUMING YONKA",
      gender: "Laki - Laki",
      birthDate: new Date("2017-10-04"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010209170003",
      name: "RAHMAT DIRGANTARA",
      gender: "Laki - Laki",
      birthDate: new Date("2017-09-02"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
],
    skipDuplicates: true,
  });
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
