import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  await prisma.user.createMany({
    data: [
     {
      nik: "3174010108151001",
      name: "Arjuna Putra Syavalani",
      gender: "Laki - Laki",
      birthDate: new Date("2015-08-01"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012006091001",
      name: "Ahmad Firmansyah",
      gender: "Laki - Laki",
      birthDate: new Date("2009-06-20"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016804141002",
      name: "NAGITA SILVYNA HERMANSYAH",
      gender: "Perempuan",
      birthDate: new Date("2014-04-28"),
      school: "SDN 03",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Belum",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174012411170002",
      name: "Muhammad Abidzar Aqil Abziansyah",
      gender: "Laki - Laki",
      birthDate: new Date("2017-11-24"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015501160007",
      name: "Alisnya Dwiandra Ainun",
      gender: "Perempuan",
      birthDate: new Date("2016-01-15"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174021803111004",
      name: "Kahfi Akhyar Zikrul Aryandi",
      gender: "Laki - Laki",
      birthDate: new Date("2011-03-18"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016711180002",
      name: "Azkia Novianti",
      gender: "Perempuan",
      birthDate: new Date("2018-11-27"),
      school: "Lainya",
      class: "1",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016906151006",
      name: "CLARISSA PUTRI HERMALIA",
      gender: "Perempuan",
      birthDate: new Date("2015-06-29"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012212131003",
      name: "MUHAMMAD FAHMI KAMIL",
      gender: "Laki - Laki",
      birthDate: new Date("2013-12-22"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174015703170004",
      name: "Khayla Almira Azzahra",
      gender: "Perempuan",
      birthDate: new Date("2017-03-17"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012802141006",
      name: "Raffi Rizky Syaputra",
      gender: "Laki - Laki",
      birthDate: new Date("2014-01-28"),
      school: "SDN 01",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010906170004",
      name: "RADITYA EMYR ADIWIJAYA",
      gender: "Laki - Laki",
      birthDate: new Date("2017-06-09"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "317401205151008",
      name: "Rendy Putra Firiyandi",
      gender: "Laki - Laki",
      birthDate: new Date("2015-05-29"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010112131006",
      name: "Ramdzi Rafa maher",
      gender: "Laki - Laki",
      birthDate: new Date("2013-12-10"),
      school: "SDN 01",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "1302106008180001",
      name: "Michelle Anggina",
      gender: "Perempuan",
      birthDate: new Date("2018-08-20"),
      school: "Lainya",
      class: "1",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011512131002",
      name: "Muhammad Abhindra Rasya",
      gender: "Laki - Laki",
      birthDate: new Date("2013-12-15"),
      school: "SDN 01",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "31740108101310004",
      name: "Bastian Maulana Ibrahim",
      gender: "Laki - Laki",
      birthDate: new Date("2013-10-08"),
      school: "SDN 01",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174012007160001",
      name: "Muhammad Rakha Fitrah",
      gender: "Laki - Laki",
      birthDate: new Date("2016-07-20"),
      school: "SDN 01",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174024410151001",
      name: "ANINDITA RAYA JASMINA",
      gender: "Perempuan",
      birthDate: new Date("2015-10-04"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015407160002",
      name: "Rakhshandrina Kaysa",
      gender: "Perempuan",
      birthDate: new Date("2016-07-14"),
      school: "SDN 01",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010610170001",
      name: "Muhammad Albert Al Bakri",
      gender: "Laki - Laki",
      birthDate: new Date("2017-10-06"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010712141005",
      name: "Muhammad Kenzo Al Bakri",
      gender: "Laki - Laki",
      birthDate: new Date("2014-12-07"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3674061103130003",
      name: "BINTANG FIRSTIAN",
      gender: "Laki - Laki",
      birthDate: new Date("2013-03-11"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Belum",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174012004160007",
      name: "Muhammad Ali Firmansyah",
      gender: "Laki - Laki",
      birthDate: new Date("2016-04-20"),
      school: "SDN 03",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174015104160002",
      name: "Kimora Sachi aruna Sofyan",
      gender: "Perempuan",
      birthDate: new Date("2016-01-11"),
      school: "SDN 01",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Sudah",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174010805131010",
      name: "Fadlan Jaya Saputra",
      gender: "Laki - Laki",
      birthDate: new Date("2013-05-08"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3674062202141001",
      name: "ADTYA SYAHMI",
      gender: "Laki - Laki",
      birthDate: new Date("2014-02-22"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Belum",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3175021307141004",
      name: "Nabil Alhafiz",
      gender: "Laki - Laki",
      birthDate: new Date("2014-07-13"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174016301170001",
      name: "KEISHA FAUZIE",
      gender: "Perempuan",
      birthDate: new Date("2017-01-23"),
      school: "Lainya",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011606160006",
      name: "Irsyad Aryasatya Salam",
      gender: "Laki - Laki",
      birthDate: new Date("2016-06-16"),
      school: "Lainya",
      class: "2",
      imunMR: "Belum",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3201160208150001",
      name: "Hamizan Adnan khiar",
      gender: "Laki - Laki",
      birthDate: new Date("2015-08-02"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016406170001",
      name: "Annasya Adreena Saila",
      gender: "Perempuan",
      birthDate: new Date("2017-06-24"),
      school: "SDN 03",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174026506141001",
      name: "Nabila junisha wilpiandi",
      gender: "Perempuan",
      birthDate: new Date("2014-06-25"),
      school: "SDN 01",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Belum",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174016111131002",
      name: "Hanifah Azzahra",
      gender: "Perempuan",
      birthDate: new Date("2013-11-21"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Belum",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "317401130613008",
      name: "VERON ZAY",
      gender: "Laki - Laki",
      birthDate: new Date("2013-06-13"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010409160003",
      name: "Andi Syaputra yan",
      gender: "Laki - Laki",
      birthDate: new Date("2016-09-04"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016504160005",
      name: "Naira Alesha noer",
      gender: "Perempuan",
      birthDate: new Date("2016-04-10"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Sudah",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174016208170003",
      name: "Shafa ashalina noer",
      gender: "Perempuan",
      birthDate: new Date("2017-08-22"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Sudah",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "31740150007131002",
      name: "Zaeda Marhamah",
      gender: "Perempuan",
      birthDate: new Date("2013-07-10"),
      school: "SDN 03",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016904170004",
      name: "Nafisha Azzahra",
      gender: "Perempuan",
      birthDate: new Date("2017-04-29"),
      school: "SDN 03",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014802170004",
      name: "Delia Febrianti Anggaraeni",
      gender: "Perempuan",
      birthDate: new Date("2017-02-08"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015208170003",
      name: "Arsyila Romeesa Farzana",
      gender: "Perempuan",
      birthDate: new Date("2017-08-12"),
      school: "SDN 01",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "331237101140001",
      name: "Arneyla innata kea labiqa",
      gender: "Perempuan",
      birthDate: new Date("2014-01-31"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Belum",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174092109131006",
      name: "Fakhri rafi rabbani",
      gender: "Laki - Laki",
      birthDate: new Date("2013-09-21"),
      school: "SDN 01",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174010511131002",
      name: "Javario akma bre rajendra",
      gender: "Laki - Laki",
      birthDate: new Date("2013-11-01"),
      school: "SDN 01",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174014803151006",
      name: "Khalila Almira maritza",
      gender: "Perempuan",
      birthDate: new Date("2015-03-08"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Sudah",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174011209160005",
      name: "Kynan azka airlangga",
      gender: "Laki - Laki",
      birthDate: new Date("2016-09-12"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012806180007",
      name: "Haldi Syaputra",
      gender: "Laki - Laki",
      birthDate: new Date("2016-03-17"),
      school: "SDN 03",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174012006141001",
      name: "Azalea zaura kiandra firmansyah",
      gender: "Perempuan",
      birthDate: new Date("2016-09-18"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "31740164080160003",
      name: "Azkia Mutiara Putri",
      gender: "Perempuan",
      birthDate: new Date("2016-08-24"),
      school: "SDN 03",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014901151002",
      name: "Jihan Talita ulfa",
      gender: "Perempuan",
      birthDate: new Date("2015-01-09"),
      school: "SDIT Assyafi'iyah",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Sudah",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "317401281016004",
      name: "Muhammad Triandi",
      gender: "Laki - Laki",
      birthDate: new Date("2016-10-28"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014204180003",
      name: "Zahratul humaerah",
      gender: "Perempuan",
      birthDate: new Date("2018-04-02"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Sudah",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174012609151007",
      name: "Muhammad Rafie Adha",
      gender: "Laki - Laki",
      birthDate: new Date("2015-09-26"),
      school: "SDN 03",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "31740112101310002",
      name: "Ismail Azzam Abdillah",
      gender: "Laki - Laki",
      birthDate: new Date("2013-10-12"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016901160001",
      name: "Hanum Farah nazwala",
      gender: "Perempuan",
      birthDate: new Date("2016-01-29"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Sudah",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "327202004150003",
      name: "Arsakha Ruan Khaleev",
      gender: "Laki - Laki",
      birthDate: new Date("2016-04-20"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015208151001",
      name: "Annisa Naura alby",
      gender: "Perempuan",
      birthDate: new Date("2015-08-12"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Sudah",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174014411150002",
      name: "Aisyah Humaira santoso",
      gender: "Perempuan",
      birthDate: new Date("2015-11-04"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014212170002",
      name: "Mikhayla Halimah Azzahra",
      gender: "Perempuan",
      birthDate: new Date("2017-12-02"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012509160004",
      name: "Zamir Mauludi",
      gender: "Laki - Laki",
      birthDate: new Date("2016-09-25"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016808170004",
      name: "Azkhaina yazna malaika",
      gender: "Perempuan",
      birthDate: new Date("2017-08-28"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Sudah",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "31740148011510006",
      name: "Nur Maspupah",
      gender: "Perempuan",
      birthDate: new Date("2015-01-08"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012801141006",
      name: "Raffi Rizky Syaputra",
      gender: "Laki - Laki",
      birthDate: new Date("2014-01-28"),
      school: "SDN 01",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016906151007",
      name: "Kanza mubarokah hariz",
      gender: "Perempuan",
      birthDate: new Date("2015-08-29"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Sudah",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174016610160006",
      name: "Aqilla Balqis Fitriah",
      gender: "Perempuan",
      birthDate: new Date("2016-10-26"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015407170003",
      name: "Nadita Wulandari Ayu Kencana",
      gender: "Perempuan",
      birthDate: new Date("2017-07-14"),
      school: "SDN 01",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174014706141002",
      name: "Keisha Andini",
      gender: "Perempuan",
      birthDate: new Date("2014-06-07"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174013107180006",
      name: "Muhammad safi'ie hariz",
      gender: "Laki - Laki",
      birthDate: new Date("2018-07-31"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174016201141004",
      name: "Azzahra hadi putri wulandari",
      gender: "Perempuan",
      birthDate: new Date("2014-01-22"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "1271214311160005",
      name: "Nadifa mursyida izzati",
      gender: "Perempuan",
      birthDate: new Date("2016-11-03"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Sudah",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3175012506151003",
      name: "Ghani Zhafran Ramadhan",
      gender: "Laki - Laki",
      birthDate: new Date("2015-06-25"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3175014908170002",
      name: "Azkadina Namira",
      gender: "Perempuan",
      birthDate: new Date("2017-08-09"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "180753107130001",
      name: "M. Fadlan Al Habsyi",
      gender: "Laki - Laki",
      birthDate: new Date("2013-07-31"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174016894151004",
      name: "RISQIA AMELIA PUTRI",
      gender: "Perempuan",
      birthDate: new Date("2015-04-28"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3175061301131014",
      name: "Ibrahim Wijaya Tjandra",
      gender: "Laki - Laki",
      birthDate: new Date("2013-01-13"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174015402180008",
      name: "Milena Lova",
      gender: "Perempuan",
      birthDate: new Date("2018-02-14"),
      school: "Lainya",
      class: "1",
      imunMR: "Belum",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "31740152088151008",
      name: "Tania Asep Audina",
      gender: "Perempuan",
      birthDate: new Date("2015-08-12"),
      school: "SDN 01",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174092906170007",
      name: "Rasqa Alfarezel Firdaus",
      gender: "Laki - Laki",
      birthDate: new Date("2017-06-29"),
      school: "SDN 01",
      class: "2",
      imunMR: "Belum",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015006151008",
      name: "Afrida sari febriani",
      gender: "Perempuan",
      birthDate: new Date("2015-06-10"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011807170006",
      name: "Renatan Alwinata",
      gender: "Laki - Laki",
      birthDate: new Date("2017-07-18"),
      school: "SDN 01",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011212170002",
      name: "Ahmad Khaisar Husein",
      gender: "Laki - Laki",
      birthDate: new Date("2017-12-12"),
      school: "Lainya",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174011801160004",
      name: "Khalif Al Askhan",
      gender: "Laki - Laki",
      birthDate: new Date("2016-01-18"),
      school: "Lainya",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010502180002",
      name: "Daffa alfarizky saputra",
      gender: "Laki - Laki",
      birthDate: new Date("2018-02-05"),
      school: "Lainya",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174016510131003",
      name: "Devita wibisono",
      gender: "Perempuan",
      birthDate: new Date("2013-10-25"),
      school: "SDN 03",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Sudah",
      imunHPV6: "Belum",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174012702141003",
      name: "Gilang Adi Febrian",
      gender: "Laki - Laki",
      birthDate: new Date("2014-02-27"),
      school: "SDN 03",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010508170005",
      name: "Muhammad Ahfan Assegaf",
      gender: "Laki - Laki",
      birthDate: new Date("2017-08-05"),
      school: "SDN 03",
      class: "2",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012709160004",
      name: "Arkha Raid Albi Zhafran",
      gender: "Laki - Laki",
      birthDate: new Date("2016-09-27"),
      school: "SDN 03",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174021506151003",
      name: "Laqif reanka anaqie",
      gender: "Laki - Laki",
      birthDate: new Date("2015-06-15"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174010901180005",
      name: "M.Bachtiar Ghifary",
      gender: "Laki - Laki",
      birthDate: new Date("2018-01-09"),
      school: "Lainya",
      class: "1",
      imunMR: "Sudah",
      imunDT: "Belum",
      imunTd: "Belum",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3276084310140002",
      name: "Syfa Aulia Zahra",
      gender: "Perempuan",
      birthDate: new Date("2014-10-03"),
      school: "SDN 03",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174015701160006",
      name: "Vanesa Rayana",
      gender: "Perempuan",
      birthDate: new Date("2016-01-17"),
      school: "SDN 03",
      class: "3",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3274016109131004",
      name: "Jessica anindya f",
      gender: "Perempuan",
      birthDate: new Date("2013-09-21"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012702141003",
      name: "Gilang Adi Febrian",
      gender: "Laki - Laki",
      birthDate: new Date("2014-02-27"),
      school: "SDN 03",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Belum",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174016607151003",
      name: "Alysa anindya F",
      gender: "Perempuan",
      birthDate: new Date("2015-07-26"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174012002141001",
      name: "M bagas prayoga",
      gender: "Laki - Laki",
      birthDate: new Date("2014-02-20"),
      school: "Lainya",
      class: "5",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174010209131004",
      name: "M AQil",
      gender: "Laki - Laki",
      birthDate: new Date("2013-09-02"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174015401170003",
      name: "Aliyah nur maulida",
      gender: "Perempuan",
      birthDate: new Date("2017-01-14"),
      school: "Lainya",
      class: "4",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Belum",
      imunHPV6: "Belum",
      status: "Tidak Lengkap",
      role: "user",
    },
    {
      nik: "3174010702141005",
      name: "Davino arman p",
      gender: "Laki - Laki",
      birthDate: new Date("2014-02-07"),
      school: "SDN 03",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
    {
      nik: "3174012006131008",
      name: "DENNIS ANDREAS PETRA BAGENDA",
      gender: "Laki - Laki",
      birthDate: new Date("2013-06-20"),
      school: "Lainya",
      class: "6",
      imunMR: "Sudah",
      imunDT: "Sudah",
      imunTd: "Sudah",
      imunTD: "Sudah",
      imunHPV5: "Laki - Laki",
      imunHPV6: "Laki - Laki",
      status: "Lengkap",
      role: "user",
    },
],
    skipDuplicates: true,
  });
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
